--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 24/11/2019 15:53:34
-- Server version: 8.0.13-4
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS `53WNcTU5Dt`;

CREATE DATABASE IF NOT EXISTS `53WNcTU5Dt`
	CHARACTER SET utf8
	COLLATE utf8_unicode_ci;

--
-- Set default database
--
USE `53WNcTU5Dt`;

--
-- Create table `tblusers`
--
CREATE TABLE IF NOT EXISTS tblusers (
  userID INT(11) NOT NULL AUTO_INCREMENT,
  userName VARCHAR(255) NOT NULL,
  userFirstName VARCHAR(255) NOT NULL,
  userLastName VARCHAR(255) NOT NULL,
  userEmail VARCHAR(255) NOT NULL,
  userPhoneNo VARCHAR(11) NOT NULL,
  userDateJoined DATE NOT NULL,
  userPassword VARCHAR(40) NOT NULL,
  PRIMARY KEY (userID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 19,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `userEmail_Unique` on table `tblusers`
--
ALTER TABLE tblusers 
  ADD UNIQUE INDEX userEmail_Unique(userEmail);

--
-- Create index `UserName_Unique` on table `tblusers`
--
ALTER TABLE tblusers 
  ADD UNIQUE INDEX UserName_Unique(userName);

--
-- Create table `tblrelationships`
--
CREATE TABLE IF NOT EXISTS tblrelationships (
  relID INT(11) NOT NULL AUTO_INCREMENT,
  relPatientID INT(11) NOT NULL,
  relCarerID INT(11) DEFAULT NULL,
  relStartDate DATE DEFAULT NULL,
  relEndDate DATE DEFAULT NULL,
  relJoinNUm VARCHAR(10) NOT NULL,
  relJoinNumDate DATE NOT NULL,
  PRIMARY KEY (relID)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `relCarerID` on table `tblrelationships`
--
ALTER TABLE tblrelationships 
  ADD INDEX relCarerID(relCarerID);

--
-- Create index `relPatientID` on table `tblrelationships`
--
ALTER TABLE tblrelationships 
  ADD INDEX relPatientID(relPatientID);

--
-- Create index `relRandNum_Unique` on table `tblrelationships`
--
ALTER TABLE tblrelationships 
  ADD UNIQUE INDEX relRandNum_Unique(relJoinNUm);

--
-- Create table `tbleventtype`
--
CREATE TABLE IF NOT EXISTS tbleventtype (
  eventTypeID INT(11) NOT NULL AUTO_INCREMENT,
  eventDesc VARCHAR(255) NOT NULL,
  PRIMARY KEY (eventTypeID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `tblevents`
--
CREATE TABLE IF NOT EXISTS tblevents (
  eventID INT(11) NOT NULL AUTO_INCREMENT,
  eventType INT(11) NOT NULL DEFAULT 1,
  eventStartDate DATE NOT NULL,
  eventTimeReport VARCHAR(8) NOT NULL DEFAULT '00:00:00',
  eventAcknowledged DATETIME DEFAULT NULL,
  eventReminderDElay DOUBLE NOT NULL DEFAULT 10,
  eventOverdueActionToTake INT(11) NOT NULL DEFAULT 2,
  eventOverdueLengthLive INT(11) NOT NULL DEFAULT 30,
  eventDescription VARCHAR(1024) NOT NULL,
  eventImg VARCHAR(255) DEFAULT NULL,
  eventRepeat TINYINT(1) NOT NULL DEFAULT 1,
  eventTimes VARCHAR(255) DEFAULT NULL,
  eventRepeatFrequency INT(11) DEFAULT NULL,
  eventStopDate DATE DEFAULT NULL,
  eventKeepLength INT(11) NOT NULL DEFAULT 14,
  eventPatientID INT(11) NOT NULL,
  eventDescShort VARCHAR(45) NOT NULL,
  PRIMARY KEY (eventID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 10,
AVG_ROW_LENGTH = 4096,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `eventOverdueActionToTake` on table `tblevents`
--
ALTER TABLE tblevents 
  ADD INDEX eventOverdueActionToTake(eventOverdueActionToTake);

--
-- Create index `eventPatientID` on table `tblevents`
--
ALTER TABLE tblevents 
  ADD INDEX eventPatientID(eventPatientID);

--
-- Create index `eventType` on table `tblevents`
--
ALTER TABLE tblevents 
  ADD INDEX eventType(eventType);

--
-- Create table `tbleventlog`
--
CREATE TABLE IF NOT EXISTS tbleventlog (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  UserID INT(11) NOT NULL,
  Description VARCHAR(255) NOT NULL,
  DateTime VARCHAR(255) NOT NULL,
  Acknowledged TINYINT(1) NOT NULL DEFAULT 0,
  KeepLength INT(11) NOT NULL,
  DateAdded DATE NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;

--
-- Create table `tblevenoverdueactions`
--
CREATE TABLE IF NOT EXISTS tblevenoverdueactions (
  eventOverdueActionID INT(11) NOT NULL AUTO_INCREMENT,
  eventOverdueAction VARCHAR(255) NOT NULL,
  PRIMARY KEY (eventOverdueActionID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;